# Basic of Numpy

In [1]:
import numpy as np

### Creating numpy array


In [2]:
new_array = np.array([1, 2, 3])

In [3]:
new_array

array([1, 2, 3])

### Check the shape of np array

In [4]:
new_array.shape

(3,)

### Get Dimentions of np array

In [5]:
new_array.ndim

1

### NumPy love math

In [6]:
np.sqrt(new_array)

array([1.        , 1.41421356, 1.73205081])

In [7]:
np.log(new_array)

array([0.        , 0.69314718, 1.09861229])

In [8]:
np.exp(new_array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [9]:
np.tanh(new_array)

array([0.76159416, 0.96402758, 0.99505475])

### Linear Algebra

In [11]:
np.linalg.norm(new_array)

3.7416573867739413

### Broadcasting

In [12]:
x = np.ones((2, 2))
y = np.ones((3, 2, 1))

In [13]:
x

array([[1., 1.],
       [1., 1.]])

In [14]:
y

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [15]:
x + y

array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

#### NumPy and matrices

In [16]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[4, 5], [6, 7]])

In [17]:
x.dot(y)

array([[16, 19],
       [36, 43]])

In [18]:
x @ y

array([[16, 19],
       [36, 43]])

### Inverse and transpose

In [19]:
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
x.T

array([[1, 3],
       [2, 4]])

### Eigen value and eigen vector

In [21]:
np.linalg.eigvals(x)

array([-0.37228132,  5.37228132])

### Changing Shape

In [22]:
x.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

### Flattening

In [23]:
x.flatten()

array([1, 2, 3, 4])

In [24]:
x_list = [[1, 2], [3, 4]]
np.ravel(x_list)

array([1, 2, 3, 4])

### Add new diminsion

In [25]:
y = np.array([1, 2, 3, 4, 5])
y[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

### Split array into new section

In [26]:
x =  np.array([0, 1, 2, 3, 4, 5,6, 7, 8])

In [27]:
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

### Data generation with numpy

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.random.rand(2, 3)

array([[0.9304538 , 0.40540704, 0.27532154],
       [0.6998769 , 0.55414395, 0.18964909]])

In [43]:
np.random.randn(2, 3)

array([[-0.00483391,  0.5004489 ,  1.09162051],
       [-0.27142877, -1.10895607,  1.28577561]])

In [36]:
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])