## Essential Guide to NumPy for machine learning in Python
Numpy is a a library for the python programming language, adding supports for large multi-dimensional array and martics, along with large collection of high level mathematical function to operate on these array.

In [1]:
import numpy as np

## 1. Creating a Vector

In [2]:
vector_row = np.array([1, 2, 3])
vector_column = np.array([[1], [2], [3]])

In [3]:
vector_row

array([1, 2, 3])

In [4]:
vector_column

array([[1],
       [2],
       [3]])

## 2. Creating a Matrix

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 5]])

In [6]:
matrix

array([[1, 2, 3],
       [4, 5, 5]])

## 3. Creating a Sparse Matrxi
Given data with very few non zero values you want to respresent efficently represent it

In [7]:
# create a matrxi
matrxi = np.array([[0, 0], [0, 1], [3, 0]])

# create a compresed sparse row (CSR) matrix
# matrxi_sparse = sparse.csr_matrxi(matrxi)

## 4. Selecting Elements

In [8]:
vector_row = np.array([1, 2, 3, 4])
matrxi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# selectig 3rd element of vector
print(vector_row[2])

# selecting 2nd row and 3rd column of matrxi
print(matrxi[1, 2])

# selecting all element of a vector
print(matrix[:])

# selecting everything upto and including the 3rd element
print(vector_row[:2])

# selecting upto 2nd row and 2nd element in each row
print(matrix[:2, :2])

3
6
[[1 2 3]
 [4 5 5]]
[1 2]
[[1 2]
 [4 5]]


In [9]:
# selecting everything after 3rd element 
print(vector_row[3:])

# select last element 
print(vector_row[-1])

# select the first 2 rows and all the columns of the matrix 
print(matrix[:2, :])

# selecting all rows and the 2nd column of the matrix 
print(matrix[:, 1:2])

[4]
4
[[1 2 3]
 [4 5 5]]
[[2]
 [5]]


## 5. Describing a matrix

In [10]:
# view number of rows and columns of matrix
print(matrix.shape)

(2, 3)


In [11]:
# view size of matrix =  rows * cloumn
matrix.size

6

In [12]:
# view dimensions of matrix
matrix.ndim

2

## 6. Applying operations to elements 
applying some function to multiple elements in an array

In [13]:
matrxi = np.array([[1, 2, 3, 4], [3, 4, 5, 6], [7, 8, 9, 10]])

In [14]:
# creating a lambda function 
lambda_function = lambda i: i +100

In [15]:
# convert it into vectorize funtion
vectorize_function = np.vectorize(lambda_function)

In [16]:
# apply funtions to all elements in matri
vectorize_function(matrix)


array([[101, 102, 103],
       [104, 105, 105]])

## 7. Finding Max and Min Values

In [17]:
np.max(matrix)

5

In [18]:
np.min(matrix)

1

In [19]:
# find max element in each column
np.max(matrix, axis = 0)

array([4, 5, 5])

In [20]:
# find max element in each row
np.max(matrix, axis = 1)

array([3, 5])

## 8. Calculating Average,Varrience and Standard Devation

In [21]:
# mean
np.mean(matrix)

3.3333333333333335

In [22]:
# standard devation
np.std(matrix)

1.4907119849998598

In [23]:
# Varience
np.var(matrix)

2.2222222222222223

## 9. Reshaping Arrays

In [24]:
new_matrix = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

In [25]:
new_matrix.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 7,  8],
       [ 9, 10]])

In [26]:
# here -1 says as many colmn as needed and 1 row
new_matrix.reshape(2, -1)

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

In [27]:
new_matrix.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [28]:
# if only one argument is given a 1-d array of that length will be created
new_matrix.reshape(12)

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [29]:
# flatten method can also used to create 1-d array of given matrix
new_matrix.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

## 10. Transposing a vector or matrix

In [30]:
new_matrix.T

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

### 11. Finding the Determinant and Rank of a Matrix
The rank of a Matrix is the number of dimension of the vecor space spanned by its row or column

In [31]:
# calculating determinant
new_matrix = np.array([[2, 4, 6], [3, 6, 9], [2, 3, 5]])
np.linalg.det(new_matrix)

0.0

In [32]:
# calculating the rank of matrix
np.linalg.matrix_rank(new_matrix)

2

## 12. Getting the Diagonal of a Matrix

In [33]:
# print the principal diagnol 
new_matrix.diagonal()

array([2, 6, 5])

In [34]:
# print the diagnol one above the principal diagonal
matrix.diagonal(offset = 1)

array([2, 5])

In [35]:
# print the diagonal one below the principal diagonal
matrix.diagonal(offset = -1)

array([4])

## 13. Calculate the trace of the matrix
Trace of a matrix is the sum of elements on the principal diagonal of the matrix  

In [36]:
matrix.trace()

6

## Finding Eigenvalues and Eignevectors
Eigenvalues are widely used in machine learning libraries. Intituatively given a linear transformation represnented by a matrix. A, eigenvectors are vectors that when that transformation is applied, change only in scale(not direction).More formally
**Av=Kv**
Here A is a square matrix, K contains the eigenvalues and v contains the eigenvectors.  

In [37]:
eigenvalues, eigenvectors = np.linalg.eig(new_matrix) 

In [38]:
eigenvalues

array([1.29226163e+01, 7.90138490e-15, 7.73837107e-02])

In [39]:
eigenvectors

array([[ 0.50487569,  0.57735027, -0.44750227],
       [ 0.75731354,  0.57735027, -0.6712534 ],
       [ 0.41421822, -0.57735027,  0.59089812]])

## 15. calculating dot products

In [40]:
vector_one = np.array([1, 2, 3])
vector_two = np.array([3, 6, 9])

In [41]:
np.dot(vector_one, vector_two)

42

In [42]:
vector_one @ vector_two

42

## 16. Adding Subtracting and Multiplying Matrices

In [43]:
matrix_1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix_2 = np.array([[6, 7, 8], [9, 10, 11]])

In [44]:
np.add(matrix_1, matrix_2)

array([[ 7,  9, 11],
       [13, 15, 17]])

In [45]:
np.subtract(matrix_1, matrix_2)

array([[-5, -5, -5],
       [-5, -5, -5]])

In [46]:
matrix_1 * matrix_2

array([[ 6, 14, 24],
       [36, 50, 66]])

## 17. Inverting a Squar Matrix
Inverse of a squar matrix

In [47]:
matrix = np.array([[1, 2], [3, 4]])
np.linalg.inv(matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## 18. Generating Randome values

In [48]:
# set a seed value
np.random.seed(1)

In [49]:
# generating 3 random integers between 1 and 10
np.random.randint(0, 11, 3)

array([5, 8, 9])

In [50]:
# draw 3 numbers from a normal distribution with mean 1.0 and std 2.0
np.random.normal(1.0, 2.0, 3)

array([-0.60434568,  0.10224438, -1.21187015])